---
- name: Create configuration for hosts to monitor
  template:
    dest=/etc/shinken/hosts/{{ hostvars[item]['ansible_hostname'] }}.cfg
    src=shinken-hosts.tmpl
  when: hostvars[item]['ansible_hostname'] is defined
  with_items: shinken_targets

# TODO: figure out how to set the parent node per host in a useful way.
#   with_items: groups['all']

