---
- name: Install Shinken from OS packages
  when: shinken_install_from == "packages"
  package: 
    name: shinken
    state: present

- name: Install Shinken using pip
  when: shinken_install_from == "pip"
  pip: 
    name: Shinken
    state: present
#    virtualenv: "{{ shinken_virtualenv }}"
#    virtualenv_site_packages: yes

