---
- include: prepare-for-install.yml

- include: install-shinken-packages.yml

- include: configure-shinken.yml

- include: configure-shinken-webui.yml
  when: '"webui2" in shinken_broker_modules'

- include: configure-systemd.yml

