---
- name: Create shinken group
  user:
    name: shinken
    system: yes

- name: Create shinken user
  user:
    name: shinken
    comment: Created by ansible-shinken
    group: shinken
    system: yes

# needed to install shinken and its web ui
- name: Install python-pip
  package:
    name: python-pip
    state: present

- name: Gather OS specific variables
  include_vars: "{{ ansible_os_family|lower }}.yml"

# For performing various checks
# FIXME: this will need tweaking to support centos.
- name: Install check dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ shinken_monitoring_plugins }}"
