---
- name: Validate configuration
  # Service command can't be used as it doesn't support 'check'
  command: service shinken check

- name: restart shinken arbiter
  service: name=shinken-arbiter state=restarted

- name: restart shinken broker
  service: name=shinken-broker state=restarted

